# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20180416_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Título do Evento'),
        ),
    ]
