# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20180423_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nome',
            new_name='titulo',
        ),
    ]
