# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20180423_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(default='Teresina', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='UFPI', max_length=150, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.CharField(default='PI', max_length=2, verbose_name='UF'),
        ),
    ]
