# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20180423_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
    ]
